services:
  api:
    build: .
    container_name: ticket_api_service
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/casedb
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: ticket_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    command: >
      mongod
      --bind_ip_all
      --quiet

volumes:
  mongo-data: